after_success edit

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -41,7 +41,19 @@ script:
 after_success:
   - test "$TRAVIS_EVENT_TYPE" = "pull_request" && make push
   - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make release || echo "success"
-  - make multi-arch
+  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != "development"
+      curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
+      python travis_after_all.py https://travis.ibm.com/api
+      export $(cat .to_export_back)
+      if [[ "$BUILD_LEADER" == "YES" ]]; then
+        if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
+          echo "All jobs succeeded! Creating multi arch image..."
+          make docker:manifest-tool
+          make docker:multi-arch
+        else
+          echo "Some jobs failed" && exit 1
+        fi
+      fi
   - make cicd-log-success
 
 after_failure:
